"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AccountSubtype;
(function (AccountSubtype) {
    AccountSubtype[AccountSubtype["_401a"] = '401a'] = "_401a";
    AccountSubtype[AccountSubtype["_401k"] = '401k'] = "_401k";
    AccountSubtype[AccountSubtype["_403B"] = '403B'] = "_403B";
    AccountSubtype[AccountSubtype["_457b"] = '457b'] = "_457b";
    AccountSubtype[AccountSubtype["_529"] = '529'] = "_529";
    AccountSubtype[AccountSubtype["Brokerage"] = 'brokerage'] = "Brokerage";
    AccountSubtype[AccountSubtype["CashIsa"] = 'cash isa'] = "CashIsa";
    AccountSubtype[AccountSubtype["EducationSavingsAccount"] = 'education savings account'] = "EducationSavingsAccount";
    AccountSubtype[AccountSubtype["Gic"] = 'gic'] = "Gic";
    AccountSubtype[AccountSubtype["HealthReimbursementArrangement"] = 'health reimbursement arrangement'] = "HealthReimbursementArrangement";
    AccountSubtype[AccountSubtype["Hsa"] = 'hsa'] = "Hsa";
    AccountSubtype[AccountSubtype["Isa"] = 'isa'] = "Isa";
    AccountSubtype[AccountSubtype["Ira"] = 'ira'] = "Ira";
    AccountSubtype[AccountSubtype["Lif"] = 'lif'] = "Lif";
    AccountSubtype[AccountSubtype["Lira"] = 'lira'] = "Lira";
    AccountSubtype[AccountSubtype["Lrif"] = 'lrif'] = "Lrif";
    AccountSubtype[AccountSubtype["Lrsp"] = 'lrsp'] = "Lrsp";
    AccountSubtype[AccountSubtype["NonTaxableBrokerageAccount"] = 'non-taxable brokerage account'] = "NonTaxableBrokerageAccount";
    AccountSubtype[AccountSubtype["Other"] = 'other'] = "Other";
    AccountSubtype[AccountSubtype["Prif"] = 'prif'] = "Prif";
    AccountSubtype[AccountSubtype["Rdsp"] = 'rdsp'] = "Rdsp";
    AccountSubtype[AccountSubtype["Resp"] = 'resp'] = "Resp";
    AccountSubtype[AccountSubtype["Rlif"] = 'rlif'] = "Rlif";
    AccountSubtype[AccountSubtype["Rrif"] = 'rrif'] = "Rrif";
    AccountSubtype[AccountSubtype["Pension"] = 'pension'] = "Pension";
    AccountSubtype[AccountSubtype["ProfitSharingPlan"] = 'profit sharing plan'] = "ProfitSharingPlan";
    AccountSubtype[AccountSubtype["Retirement"] = 'retirement'] = "Retirement";
    AccountSubtype[AccountSubtype["Roth"] = 'roth'] = "Roth";
    AccountSubtype[AccountSubtype["Roth401k"] = 'roth 401k'] = "Roth401k";
    AccountSubtype[AccountSubtype["Rrsp"] = 'rrsp'] = "Rrsp";
    AccountSubtype[AccountSubtype["SepIra"] = 'sep ira'] = "SepIra";
    AccountSubtype[AccountSubtype["SimpleIra"] = 'simple ira'] = "SimpleIra";
    AccountSubtype[AccountSubtype["Sipp"] = 'sipp'] = "Sipp";
    AccountSubtype[AccountSubtype["StockPlan"] = 'stock plan'] = "StockPlan";
    AccountSubtype[AccountSubtype["ThriftSavingsPlan"] = 'thrift savings plan'] = "ThriftSavingsPlan";
    AccountSubtype[AccountSubtype["Tfsa"] = 'tfsa'] = "Tfsa";
    AccountSubtype[AccountSubtype["Trust"] = 'trust'] = "Trust";
    AccountSubtype[AccountSubtype["Ugma"] = 'ugma'] = "Ugma";
    AccountSubtype[AccountSubtype["Utma"] = 'utma'] = "Utma";
    AccountSubtype[AccountSubtype["VariableAnnuity"] = 'variable annuity'] = "VariableAnnuity";
    AccountSubtype[AccountSubtype["CreditCard"] = 'credit card'] = "CreditCard";
    AccountSubtype[AccountSubtype["Paypal"] = 'paypal'] = "Paypal";
    AccountSubtype[AccountSubtype["Cd"] = 'cd'] = "Cd";
    AccountSubtype[AccountSubtype["Checking"] = 'checking'] = "Checking";
    AccountSubtype[AccountSubtype["Savings"] = 'savings'] = "Savings";
    AccountSubtype[AccountSubtype["MoneyMarket"] = 'money market'] = "MoneyMarket";
    AccountSubtype[AccountSubtype["Prepaid"] = 'prepaid'] = "Prepaid";
    AccountSubtype[AccountSubtype["Auto"] = 'auto'] = "Auto";
    AccountSubtype[AccountSubtype["Commercial"] = 'commercial'] = "Commercial";
    AccountSubtype[AccountSubtype["Construction"] = 'construction'] = "Construction";
    AccountSubtype[AccountSubtype["Consumer"] = 'consumer'] = "Consumer";
    AccountSubtype[AccountSubtype["Home"] = 'home'] = "Home";
    AccountSubtype[AccountSubtype["HomeEquity"] = 'home equity'] = "HomeEquity";
    AccountSubtype[AccountSubtype["Loan"] = 'loan'] = "Loan";
    AccountSubtype[AccountSubtype["Mortgage"] = 'mortgage'] = "Mortgage";
    AccountSubtype[AccountSubtype["Overdraft"] = 'overdraft'] = "Overdraft";
    AccountSubtype[AccountSubtype["LineOfCredit"] = 'line of credit'] = "LineOfCredit";
    AccountSubtype[AccountSubtype["Student"] = 'student'] = "Student";
    AccountSubtype[AccountSubtype["CashManagement"] = 'cash management'] = "CashManagement";
    AccountSubtype[AccountSubtype["Keogh"] = 'keogh'] = "Keogh";
    AccountSubtype[AccountSubtype["MutualFund"] = 'mutual fund'] = "MutualFund";
    AccountSubtype[AccountSubtype["Recurring"] = 'recurring'] = "Recurring";
    AccountSubtype[AccountSubtype["Rewards"] = 'rewards'] = "Rewards";
    AccountSubtype[AccountSubtype["SafeDeposit"] = 'safe deposit'] = "SafeDeposit";
    AccountSubtype[AccountSubtype["Sarsep"] = 'sarsep'] = "Sarsep";
})(AccountSubtype = exports.AccountSubtype || (exports.AccountSubtype = {}));
//# sourceMappingURL=accountSubtype.js.map