/// <reference types="node" />
import localVarRequest from 'request';
export * from './aPR';
export * from './account';
export * from './accountBalance';
export * from './accountSubtype';
export * from './accountType';
export * from './accountsGetRequest';
export * from './accountsGetResponse';
export * from './address';
export * from './addressData';
export * from './amount';
export * from './assetReport';
export * from './assetReportAuditCopyCreateRequest';
export * from './assetReportAuditCopyCreateResponse';
export * from './assetReportAuditCopyRemoveRequest';
export * from './assetReportAuditCopyRemoveResponse';
export * from './assetReportCreateRequest';
export * from './assetReportCreateRequestOptions';
export * from './assetReportCreateResponse';
export * from './assetReportFilterRequest';
export * from './assetReportFilterResponse';
export * from './assetReportGetRequest';
export * from './assetReportGetResponse';
export * from './assetReportItem';
export * from './assetReportPDFGetRequest';
export * from './assetReportRefreshRequest';
export * from './assetReportRefreshRequestOptions';
export * from './assetReportRefreshResponse';
export * from './assetReportRemoveRequest';
export * from './assetReportRemoveResponse';
export * from './assetReportUser';
export * from './assetsErrorWebhook';
export * from './assetsProductReadyWebhook';
export * from './authGetRequest';
export * from './authGetRequestOptions';
export * from './authGetResponse';
export * from './authGetResponseNumbers';
export * from './automaticallyVerifiedWebhook';
export * from './balanceGetRequest';
export * from './balanceGetRequestOptions';
export * from './balanceGetResponse';
export * from './categoriesGetResponse';
export * from './category';
export * from './cause';
export * from './countryCode';
export * from './creditCardLiability';
export * from './defaultUpdateWebhook';
export * from './depositSwitchCreateRequest';
export * from './depositSwitchCreateResponse';
export * from './depositSwitchTokenCreateRequest';
export * from './depositSwitchTokenCreateResponse';
export * from './email';
export * from './historicalBalance';
export * from './historicalUpdateWebhook';
export * from './holding';
export * from './holdingsDefaultUpdateWebhook';
export * from './identityGetRequest';
export * from './identityGetResponse';
export * from './inflowModel';
export * from './initialUpdateWebhook';
export * from './institution';
export * from './institutionSearchRequest';
export * from './institutionSearchRequestOptions';
export * from './institutionSearchResponse';
export * from './institutionStatus';
export * from './institutionsGetByIdRequest';
export * from './institutionsGetByIdRequestOptions';
export * from './institutionsGetByIdResponse';
export * from './institutionsGetRequest';
export * from './institutionsGetRequestOptions';
export * from './institutionsGetResponse';
export * from './investmentTransaction';
export * from './investmentsDefaultUpdateWebhook';
export * from './investmentsHoldingsGetRequest';
export * from './investmentsHoldingsGetRequestOptions';
export * from './investmentsHoldingsGetResponse';
export * from './investmentsTransactionsGetRequest';
export * from './investmentsTransactionsGetRequestOptions';
export * from './investmentsTransactionsGetResponse';
export * from './item';
export * from './itemAccessTokenInvalidateRequest';
export * from './itemAccessTokenInvalidateResponse';
export * from './itemErrorWebhook';
export * from './itemGetRequest';
export * from './itemGetResponse';
export * from './itemImportRequest';
export * from './itemImportRequestOptions';
export * from './itemImportRequestUserAuth';
export * from './itemImportResponse';
export * from './itemProductReadyWebhook';
export * from './itemPublicTokenCreateRequest';
export * from './itemPublicTokenCreateResponse';
export * from './itemPublicTokenExchangeRequest';
export * from './itemPublicTokenExchangeResponse';
export * from './itemRemoveRequest';
export * from './itemRemoveResponse';
export * from './itemStatus';
export * from './itemStatusInvestments';
export * from './itemStatusLastWebhook';
export * from './itemStatusTransactions';
export * from './itemWebhookUpdateResponse';
export * from './jWTHeader';
export * from './liabilitiesGetRequest';
export * from './liabilitiesGetRequestOptions';
export * from './liabilitiesGetResponse';
export * from './liabilitiesObject';
export * from './liabilityOverride';
export * from './linkTokenCreateRequest';
export * from './linkTokenCreateRequestAccountFilters';
export * from './linkTokenCreateRequestAccountFiltersCredit';
export * from './linkTokenCreateRequestAccountFiltersDepository';
export * from './linkTokenCreateRequestAccountFiltersInvestment';
export * from './linkTokenCreateRequestAccountFiltersLoan';
export * from './linkTokenCreateRequestPaymentInitiation';
export * from './linkTokenCreateRequestUser';
export * from './linkTokenCreateResponse';
export * from './location';
export * from './mFA';
export * from './meta';
export * from './modelError';
export * from './numbers';
export * from './numbersACH';
export * from './numbersBACS';
export * from './numbersEFT';
export * from './numbersInternational';
export * from './overrideAccounts';
export * from './owner';
export * from './ownerOverride';
export * from './pSLFStatus';
export * from './paymentAmount';
export * from './paymentInitiationAddress';
export * from './paymentInitiationPayment';
export * from './paymentInitiationPaymentCreateRequest';
export * from './paymentInitiationPaymentCreateRequestSchedule';
export * from './paymentInitiationPaymentCreateResponse';
export * from './paymentInitiationPaymentListRequest';
export * from './paymentInitiationPaymentListRequestOptions';
export * from './paymentInitiationPaymentListResponse';
export * from './paymentInitiationRecipient';
export * from './paymentInitiationRecipientCreateRequest';
export * from './paymentInitiationRecipientCreateRequestBacs';
export * from './paymentInitiationRecipientCreateResponse';
export * from './paymentInitiationRecipientGetRequest';
export * from './paymentInitiationRecipientGetResponse';
export * from './paymentInitiationRecipientListRequest';
export * from './paymentInitiationRecipientListResponse';
export * from './paymentIntiationPaymentGetRequest';
export * from './paymentIntiationPaymentGetResponse';
export * from './paymentMeta';
export * from './paymentStatusUpdateWebhook';
export * from './pendingExpirationWebhook';
export * from './phoneNumber';
export * from './processorAuthGetRequest';
export * from './processorAuthGetResponse';
export * from './processorAuthGetResponseNumbers';
export * from './processorBalanceGetRequest';
export * from './processorBalanceGetResponse';
export * from './processorIdentityGetRequest';
export * from './processorIdentityGetResponse';
export * from './processorStripeBankAccountTokenCreateRequest';
export * from './processorStripeBankAccountTokenCreateResponse';
export * from './processorTokenCreateRequest';
export * from './processorTokenCreateResponse';
export * from './productStatus';
export * from './productStatusBreakdown';
export * from './recaptchaRequiredError';
export * from './sandboxItemFireWebhookRequest';
export * from './sandboxItemFireWebhookResponse';
export * from './sandboxItemResetLoginRequest';
export * from './sandboxItemResetLoginResponse';
export * from './sandboxItemSetVerificationStatusRequest';
export * from './sandboxItemSetVerificationStatusResponse';
export * from './sandboxPublicTokenCreateRequest';
export * from './sandboxPublicTokenCreateRequestOptions';
export * from './sandboxPublicTokenCreateResponse';
export * from './security';
export * from './servicerAddressData';
export * from './standaloneAccountType';
export * from './standaloneCurrencyCodeList';
export * from './standaloneInvestmentTransactionSubtype';
export * from './standaloneInvestmentTransactionType';
export * from './studentLoan';
export * from './studentLoanRepaymentModel';
export * from './studentLoanStatus';
export * from './studentRepaymentPlan';
export * from './transaction';
export * from './transactionCode';
export * from './transactionOverride';
export * from './transactionsGetRequest';
export * from './transactionsGetRequestOptions';
export * from './transactionsGetResponse';
export * from './transactionsRefreshRequest';
export * from './transactionsRefreshResponse';
export * from './transactionsRemovedWebhook';
export * from './userCustomPassword';
export * from './userPermissionRevokedWebhook';
export * from './verificationExpiredWebhook';
export * from './warning';
export * from './webhookUpdateAcknowledgedWebhook';
export * from './webhookVerificationKeyGetRequest';
export * from './webhookVerificationKeyGetResponse';
import * as fs from 'fs';
export interface RequestDetailedFile {
    value: Buffer;
    options?: {
        filename?: string;
        contentType?: string;
    };
}
export declare type RequestFile = string | Buffer | fs.ReadStream | RequestDetailedFile;
export declare class ObjectSerializer {
    static findCorrectType(data: any, expectedType: string): any;
    static serialize(data: any, type: string): any;
    static deserialize(data: any, type: string): any;
}
export interface Authentication {
    applyToRequest(requestOptions: localVarRequest.Options): Promise<void> | void;
}
export declare class HttpBasicAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class HttpBearerAuth implements Authentication {
    accessToken: string | (() => string);
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class ApiKeyAuth implements Authentication {
    private location;
    private paramName;
    apiKey: string;
    constructor(location: string, paramName: string);
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class OAuth implements Authentication {
    accessToken: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class VoidAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(_: localVarRequest.Options): void;
}
export declare type Interceptor = (requestOptions: localVarRequest.Options) => (Promise<void> | void);
